# Generated by Django 6.1 on 2026-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='code',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('products', 'Products'), ('customers', 'Customers'), ('inventory', 'Inventory'), ('suppliers', 'Suppliers'), ('purchases', 'Purchases'), ('sales', 'Sales'), ('sales_data_access', 'Sales Data Access'), ('payments', 'Payments'), ('expenses', 'Expenses'), ('expense_categories', 'Expense Categories'), ('freezers', 'Freezers'), ('claims', 'Claims'), ('reconciliation', 'Reconciliation'), ('users', 'Users'), ('roles', 'Roles'), ('password_policies', 'Password Policies'), ('audit_logs', 'Audit Logs')], max_length=50, unique=True),
        ),
    ]
