# Generated by Django 6.1 on 2026-08-12 16:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hsn_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('cartons_per_unit', models.PositiveIntegerField(default=1)),
                ('boxes_per_carton', models.PositiveIntegerField(default=1)),
                ('pieces_per_box', models.PositiveIntegerField(default=1)),
                ('purchase_rate_per_piece', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('box_purchase_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('box_retail_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('bill_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('retail_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('new_retail_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mrp', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
