# Generated by Django 6.1 on 2026-08-12 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('customer_type', models.CharField(choices=[('VAN_ROUTE', 'Van Route'), ('RETAIL', 'Retail'), ('COUNTER', 'Counter'), ('OTHER', 'Other')], default='VAN_ROUTE', max_length=20)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.route')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
